--- 
- 
  hosts: webservers
  remote_user: root
  sudo: true
  tasks: 
    - 
      name: "test connection"
      ping: ~
      remote_user: root
      sudo: true
    - 
      name: "tomat service stopping"
      service: "name={{ service_name }} state=stopped"
    - 
      name: "Removing provision.war"
      shell: "rm -f provision.war chdir={{ dest_loc }}" 
    - 
      name: "Copy provision.war to target environment"
      copy: "src={{ war_loc }}/provision.war dest={{ dest_loc }} force=yes"
    - 
      name: "tomcat service start"
      service: "name={{ service_name }} state=restarted"
